# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


server:
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
  port: 9308
  shutdown: GRACEFUL # this will allow to finish currently processing request before shutdown. This is very important for cloud/Kube environment

eureka:
  client:
    register-with-eureka: false
    enabled: false

# OpenAPI documentation
#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: true
#  show-actuator: true
#  swagger-ui:
#    path: /api-docs/swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    operations-sorter: method

# following setting are for dealing with 404 error
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
          jwk-set-uri: ${OAUTH_JWT_SET_URI}
  application:
    name: rapidtoxapp
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true # false value is needed for json based 404 error but for static contents it has be true.
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/ # Locations of static resources
  jackson:
    serialization:
      indent_output: true
  data:
    jpa:
      repositories:
        bootstrap-mode: DEFERRED
    rest:
      return-body-on-create: false
      return-body-on-update: false
      # base-path: /
      default-media-type: application/json
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  lifecycle:
    timeout-per-shutdown-phase: 20s # this important for kube/cloud environment

#Metrics related configurations
management:
  health:
    db:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /actuator # default is actuator - now you can access /api/manage/health
      exposure:
        include: prometheus, info, health, env, refresh
  #        include: "*" # this is not good for security
  metrics:
    export:
      prometheus:
        enabled: true
  # showing more information for git in /info
  info:
    git:
      mode: full

## Spring Boot Actuator Info Endpoint Customization
info:
  # static properties
  app:
    name: ${spring.application.name}
    description: microservice for rapidtoxapp list.
  # build properties from maven
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    version: @project.version@
  # environment variables
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

#Clowder Keys
clowder:
  base-url: ${CLOWDER_BASE_URL}
  write-key: e859079e-c7fd-47a5-af57-b32ed8b34fef
  read-key: 20475380-fbd7-476c-8d78-0c261c250c98

rtplot-api:
  url: ${RTPLOT_API_ENDPOINT}
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration
#
# ===================================================================

# application:
application:
  doc-host-replacement: ccte-api-ccd-dev.epa.gov
  doc-host-port: 443
  doc-host-http-protocol: https
  start-port: 9300
  end-port: 9350
  server-port: 9300 # for non-cloud profiles

keycloak:
  username: rapidtox-view-users
  password: Rapidtox2022
  clientSecret: 4e7f6c9a-3f32-4f41-8921-63afaea69167
  clientId: realm-management
