# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: rapidtoxapp
  jackson:
    serialization:
      indent-output: true
  main:
    url: ${RAPIDTOX_CONNECTION_STRING}
    username: ${RAPIDTOX_USER}
    password: ${RAPIDTOX_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    #driver-class-name: org.postgresql.Driver
    allow-circular-references: true
    hikari:
      poolName: RapidtoxHikari1
      auto-commit: false
      minimum-idle: 2
  similarity:
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: ${RAPIDTOX_ALT_CONNECTION_STRING}
    username: ${RAPIDTOX_ALT_USER}
    password: ${RAPIDTOX_ALT_PASSWORD}
    allow-circular-references: true
    hikari:
      poolName: SimilarityHikari1
      auto-commit: false
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      #hibernate.default_schema: ccd_app
# Logging - settings
logging:
  level:
    com.zaxxer.hikari.HikariConfig: info
    org.hibernate.SQL: info
    gov.epa.ccte.api.*: info
    org.springframework: warn
    org.springframework.security: info

#Clowder Dataset Ids
clowder:
  landscape: 620bbbf3e4b039b22c79f6fb
  single: 620bbbbbe4b039b22c79f6ed
  batch: 620bbbdbe4b039b22c79f6f4

# server - gov.epa.ccte.api.rapidtox
server:
  server:
    connection-timeout:
  servlet:
    context-path: /
  #port: 9300

# sentry
sentry:
  dsn: https://98083f4581cd0bc1c76474a55b0e2c36@ccte-app-monitoring.epa.gov/17
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  environment: dev

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# multiple datasources
#app:
#  datasource:
#    pgsql:
#      type: com.zaxxer.hikari.HikariDataSource
#      url: jdbc:postgresql://ccte-pgsql-dev.epa.gov:5432/dev_datahub
#      username: app_ccd
#      password: 2peM?Mu9MNpm5v!?
