name: Docker-ghcr

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "dev", "staging", "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}


jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: USEPA/ccte-docker-build@main
        with:
          username: USEPA
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}
          build_args: APP_SERVER_ENVIRONMENT=${{ github.head_ref || github.ref_name }}
